# I am taking value of N as 1 thousand
global N=1000
#Taking array of size 1 thousand
@time ArrayA = rand(1:10,N)
# taking sum of element of array A
@time sum(ArrayA)
#creating matrix A
@time A = rand(1:10, N , N)
#Creating matrix B
@time B = rand(1:10, N, N)
#Adding matrix A and B
@time A + B
#Adding sum of element of A
@time sum(A)
#sum of diagonal element of matrix A
global diag_sum=0
for i in 1:N
diag_sum = diag_sum + (A[i,i])
end
diag_sum
using LinearAlgebra
@time diag_add = tr(A)
#Matrix Multiplication of A and C, and sored in C
@time C = A * B
#Creating function for all the above matrix operation so that we can measure time taken to run whole function
function sumMult(N)
matA = rand(1:10,N,N)
matB = rand(1:10,N,N)
diag_add = 0
Add = matA + matB
Mult = matA * matB
SumA = sum(matA)
for i in 1:N
diag_add = diag_add + (matA[i,i])
end
end
#running above function
@time sumMult(N)
using DelimitedFiles
num = 5507226
small = 55072
#creating funcition to creating file of size 100 MB and writing content from that file to another file(copy operation)
function readWrite(num)
Arr = rand(num)
writedlm("test1_created.txt", Arr)
writedlm("test2_copied.txt", readdlm("test1_created.txt"))
end
@time readWrite(num)
#creating a function to generate 100 small text files of 1MB
function Small(num)
Arr = rand(num)
writedlm("C:/Users/saura/Desktop/Smallfiles/1.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/2.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/3.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/4.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/5.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/6.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/7.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/8.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/9.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/10.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/11.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/12.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/13.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/14.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/15.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/16.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/17.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/18.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/19.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/20.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/21.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/22.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/23.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/24.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/25.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/26.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/27.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/28.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/29.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/30.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/31.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/32.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/33.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/34.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/35.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/36.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/37.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/38.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/39.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/40.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/41.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/42.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/43.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/44.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/45.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/46.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/47.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/48.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/49.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/50.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/51.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/52.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/53.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/54.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/55.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/56.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/57.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/58.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/59.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/60.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/61.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/62.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/63.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/64.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/65.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/66.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/67.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/68.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/69.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/70.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/71.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/72.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/73.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/74.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/75.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/76.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/77.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/78.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/79.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/80.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/81.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/82.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/83.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/84.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/85.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/86.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/87.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/88.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/89.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/90.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/91.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/92.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/93.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/94.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/95.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/96.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/97.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/98.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/99.txt", Arr)
writedlm("C:/Users/saura/Desktop/Smallfiles/100.txt", Arr)
end
@time Small(small)
#Creating function to copy content from all small files into one single file.
function Writefun()
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/1.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/2.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/3.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/4.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/5.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/6.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/7.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/8.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/9.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/10.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/11.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/12.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/13.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/14.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/15.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/16.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/17.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/18.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/19.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/20.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/21.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/22.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/23.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/24.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/25.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/26.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/27.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/28.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/29.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/30.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/31.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/32.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/33.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/34.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/35.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/36.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/37.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/38.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/39.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/40.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/41.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/42.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/43.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/44.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/45.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/46.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/47.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/48.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/49.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/50.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/51.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/52.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/53.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/54.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/55.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/56.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/57.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/58.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/59.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/60.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/61.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/62.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/63.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/64.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/65.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/66.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/67.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/68.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/69.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/70.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/71.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/72.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/73.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/74.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/75.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/76.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/77.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/78.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/79.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/80.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/81.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/82.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/83.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/84.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/85.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/86.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/87.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/88.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/89.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/90.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/91.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/92.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/93.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/94.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/95.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/96.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/97.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/98.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/99.txt"))
writedlm("copiedfromSmall.txt",readdlm("C:/Users/saura/Desktop/Smallfiles/100.txt"))
end
#using the function
@time Writefun()
